### ISSUE TITLE
Needs a gif.

### ISSUE THREAD

**Issue by karloluis** [JakeDixon/zip-folder#1]
I'm hesitant to add this package since I already have tons of others that cram my load time. It might help persuade me and other by having a GIF like some other packages. A simple GIF showing how to use this would be awesome.

**Comment by JakeDixon** [comment]
Thanks for the awesome feedback, it's been added as well as a few other updates to increase the functionality of the package.

**Comment by karloluis** [comment]
Looks neat. Good job.

**Comment by borisco** [comment]
Hi Jake,
Is there a way to exclude files and folders, like .git or .DS_STORE ?
Thanks
