### ISSUE TITLE
Empy zip file created with no name (just extension)

### ISSUE THREAD

**Issue by radosavljevic** [JakeDixon/zip-folder#2]
It seems that when file name contains underscore symbol `_` the plugin just makes an empty zip file with no name, it just has a zip extension (`.zip`).

**Comment by JakeDixon** [comment]
Hi, 

Which OS are you on? Just I can't replicate this on Windows 10.

Thanks

**Comment by radosavljevic** [comment]
Hi,

I was on Windows 7, but now I switched to Windows 10 and everything is fine.

**Comment by JakeDixon** [comment]
Hi, 

Great news that it is working, I don't have any machines still on windows 7 to go back and test further so I'm going to mark this as closed.

Thanks
