### ISSUE TITLE
Option to put zipped files in folder

### ISSUE THREAD

**Issue by danzen** [JakeDixon/zip-folder#4]
When I right click a folder - say myFiles - in Windows and choose send to > compressed folder... it makes a zip file with the first folder inside being myFiles.  Perhaps you could set this up as an option.  Right now, if I use your excellent software to zip in ATOM, it does not include the containing file in the zip and this runs the risk of unzipping loose - say, I unzip to the desktop - all the files at the first level inside the zip would unzip to the desktop.   I think either way is good - it would just be nice to have a choice (aside from making another containing folder and zipping that).  Thanks!

**Comment by petrchutny** [comment]
I would also welcome this as an option :) I feel like it's the expected behavior to produce a folder in the archive, because that is what I originally selected in Atom. If I'd select only the files to be zipped by your plugin, I'd expect the files to be immediately in the archive, no top folder.

**Comment by JakeDixon** [comment]
I've added an option in to the new version. I am just having some issues with apm not allowing me to publish the package correctly. I will update this again once the update is live.

**Comment by JakeDixon** [comment]
Hi Both,

Pushed the latest update manually. It's now available for you both to use.

Best regards,
Jake
